name: artifact
on: push
env: 
  artifact : test
  file-name: file

jobs: 
  job1:
   name: create and upload artifact
   runs-on: ubuntu-latest
   steps:
      - name: checkout
        uses: actions/checkout@v1
      - name: create a fil
        run: echo "testing" > ${{ env.file-name}}
      - name: upload artifact
        uses: actions/upload-artifact@v1.0.0
        with:
          name: ${{ env.artifact }}
          path: ./${{ env.file-name}}

  job2:
   name: download and print artifact
   runs-on: macos-latest
   needs: job1
   steps:
      - name: download artifact
        uses: actions/download-artifact@v1.0.0
        with: 
         name: ${{ env.artifact }}
      - name: print artifact
        run: cat ${{ env.artifact }}
    
   
